# Generated by Django 3.2.7 on 2021-11-20 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gpro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calc_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dri_oa', models.IntegerField(verbose_name='Overall')),
                ('dri_con', models.IntegerField(verbose_name='Concentration')),
                ('dri_tal', models.IntegerField(verbose_name='Talent')),
                ('dri_agg', models.IntegerField(verbose_name='Aggressiveness')),
                ('dri_exp', models.IntegerField(verbose_name='Experience')),
                ('dri_ti', models.IntegerField(verbose_name='Technical Insight')),
                ('dri_sta', models.IntegerField(verbose_name='Stamina')),
                ('dri_cha', models.IntegerField(verbose_name='Charisma')),
                ('dri_mot', models.IntegerField(verbose_name='Motivation')),
                ('dri_rep', models.IntegerField(verbose_name='Reputation')),
                ('dri_wei', models.IntegerField(verbose_name='Weight')),
                ('dri_age', models.IntegerField(verbose_name='Age')),
                ('car_cha_lvl', models.IntegerField(verbose_name='Chassis lvl')),
                ('car_cha_wear', models.IntegerField(verbose_name='Chassis Wear')),
                ('car_eng_lvl', models.IntegerField(verbose_name='Engine lvl')),
                ('car_eng_wear', models.IntegerField(verbose_name='Engine Wear')),
                ('car_fw_lvl', models.IntegerField(verbose_name='Front wing lvl')),
                ('car_fw_wear', models.IntegerField(verbose_name='Front Wing Wear')),
                ('car_rw_lvl', models.IntegerField(verbose_name='Rear wing lvl')),
                ('car_rw_wear', models.IntegerField(verbose_name='Rear wing Wear')),
                ('car_und_lvl', models.IntegerField(verbose_name='Underbody lvl')),
                ('car_und_wear', models.IntegerField(verbose_name='Underbody Wear')),
                ('car_sid_lvl', models.IntegerField(verbose_name='Sidepods lvl')),
                ('car_sid_wear', models.IntegerField(verbose_name='Sidepods Wear')),
                ('car_coo_lvl', models.IntegerField(verbose_name='Colling lvl')),
                ('car_coo_wear', models.IntegerField(verbose_name='Cooling Wear')),
                ('car_gea_lvl', models.IntegerField(verbose_name='Gearbox lvl')),
                ('car_gea_wear', models.IntegerField(verbose_name='Gearbox Wear')),
                ('car_bra_lvl', models.IntegerField(verbose_name='Brakes lvl')),
                ('car_bra_wear', models.IntegerField(verbose_name='Brakes Wear')),
                ('car_sus_lvl', models.IntegerField(verbose_name='Suspension lvl')),
                ('car_sus_wear', models.IntegerField(verbose_name='Suspension Wear')),
                ('car_ele_lvl', models.IntegerField(verbose_name='Electronics lvl')),
                ('car_ele_wear', models.IntegerField(verbose_name='Electronics Wear')),
                ('xs_wear', models.FloatField(verbose_name='Extra soft wear')),
                ('s_wear', models.FloatField(verbose_name='Soft wear')),
                ('m_wear', models.FloatField(verbose_name='Medium wear')),
                ('h_wear', models.FloatField(verbose_name='Hard wear')),
                ('r_wear', models.FloatField(verbose_name='Rain wear')),
                ('fuel_dry_wear', models.FloatField(verbose_name='Fuel dry wear')),
                ('fuel_wet_wear', models.FloatField(verbose_name='Fuel wet wear')),
                ('risk', models.IntegerField(verbose_name='Risk')),
                ('temp', models.IntegerField(verbose_name='Temperature')),
                ('hum', models.IntegerField(verbose_name='Humidity')),
                ('identifier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gpro.race', verbose_name='Wyścig')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gpro.season', verbose_name='Sezon')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gpro.track', verbose_name='Tor')),
            ],
        ),
    ]
