# Generated by Django 3.2.7 on 2021-11-20 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gpro', '0002_calc_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calc_data',
            name='identifier',
        ),
        migrations.AlterField(
            model_name='calc_data',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gpro.season', to_field='name', verbose_name='Sezon'),
        ),
        migrations.AlterField(
            model_name='calc_data',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gpro.track', to_field='name', verbose_name='Tor'),
        ),
        migrations.AlterField(
            model_name='race',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gpro.season', to_field='name', verbose_name='Sezon'),
        ),
        migrations.AlterField(
            model_name='race',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gpro.track', to_field='name', verbose_name='Tor'),
        ),
        migrations.AlterField(
            model_name='season',
            name='name',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='Nazwa toru'),
        ),
    ]
